In [1]:
import pandas as pd
import numpy as np

In [2]:
# TEAM SALARIES TABLE
team_salaries = pd.read_html("https://www.hoopshype.com/salaries/teams/")[2].drop('Unnamed: 0', axis=1)
team_salaries["2025-26"] = team_salaries["2025-26"].str.split('$').str.get(-1).str.split(',').str.join("").astype(int)

year = 24
for i in range(10):
    url = "https://www.hoopshype.com/salaries/teams/?season=20" + str(year)
    salary_year = pd.read_html(url)[2]
    salary_year["20"+str(year)+"-"+str(year+1)] = salary_year["20"+str(year)+"-"+str(year+1)].str.split('$').str.get(-1).str.split(',').str.join("").astype(int)
    team_salaries = team_salaries.merge(salary_year, on='Team').drop('Unnamed: 0', axis=1)
    year-=1

order=['Team', '2015-16', '2016-17', '2017-18', '2018-19', '2019-20', '2020-21', '2021-22', '2022-23', '2023-24', '2024-25', '2025-26']
team_salaries = team_salaries[order]

team_salaries

,Team,2015-16,2016-17,2017-18,2018-19,2019-20,2020-21,2021-22,2022-23,2023-24,2024-25,2025-26
0,Cavaliers,108300458,128522489,137722926,123255073,131059022,129605319,136385911,151966241,166874287,165110486,217367467
1,Knicks,74237021,102593418,105403130,123387454,100232129,102137151,120644081,148987936,164990518,191906878,211398842
2,Warriors,93669566,101584835,137610134,146291276,129254928,171105334,178980766,192386134,209354737,170316619,208824825
3,Rockets,87504058,90956067,119905532,126474100,128109922,131784255,132267085,137579793,149356730,163038023,199794378
4,Timberwolves,72287243,83527580,116075131,121962221,114202982,130334934,137432702,145793656,166434327,203708244,198498074
5,Lakers,72694352,94781848,103126557,107225482,123971686,139334713,164409293,169391473,169876920,192057940,197133251
6,76ers,64583220,84775343,100797386,115127167,129912339,147825311,148922969,150496913,166271894,171403241,196806002
7,Kings,70610560,95596327,99587185,101466920,113796966,106847430,130457848,139423615,153564021,167811057,193326868
8,Clippers,97019321,114756766,119093010,118026816,131506341,139722606,168378382,192905421,201366679,174124752,191938984
9,Nuggets,72589023,83836460,107543599,118327016,128746180,129793210,137963926,162338665,180922992,185864258,191600929
10,Raptors,71591189,108599970,116929373,137793831,122463495,129131910,134896484,150992313,163054678,170516134,190948711
11,Pelicans,83709371,101616451,120814452,116052756,117868297,133901495,135793968,148360910,167403924,172778396,190786965
12,Suns,68095365,89754590,92684083,108692835,98539675,128858241,136476474,176042453,193838882,220708856,190450636
13,Thunder,95708387,91230089,134534640,144916427,132017938,95774839,82022873,148856338,162515272,166418720,190319298
14,Celtics,77141919,93465326,115284776,125334993,117759332,132931565,136557646,178633307,186940921,195348491,190096720
15,Wizards,85055155,104016580,123306396,123747588,121296256,131294012,128019790,152008934,150856313,173806822,189949625
16,Magic,63199651,104096951,98700258,114394213,126095610,121739163,126786646,126107324,132643598,152308863,189903062
17,Trail Blazers,61685814,119732234,118708146,130256600,131979953,131904647,124788473,144997250,165263993,167012048,189204726
18,Pacers,71605233,90279072,95271736,110724804,112872260,130237102,138181486,125706114,148722330,169543082,188736250
19,Heat,85764781,100740770,133624374,153171497,129867871,134731235,140840240,151408266,177143542,176102077,188283014
20,Pistons,77256014,106492988,119773191,126557932,104527576,117041599,131120355,129153570,139233014,140501660,188270076
21,Hornets,76860006,103054004,117382664,121427859,96552033,108218809,122139566,125874047,140774484,168575524,188049840
22,Spurs,87832839,112017779,114633844,121588790,119217331,129537825,127655401,104545376,142867770,162395330,187455363
23,Hawks,71661760,96315163,99992696,79180081,110702618,118804016,135166020,149836313,159153393,170057021,187049086
24,Mavericks,75397067,102354966,85440245,86958881,120871082,127657823,126696965,177244238,167755884,174411922,185598396
25,Bucks,73843541,96245877,120521249,130988604,122612183,136623929,160875421,182930771,187346674,182559432,184516265
26,Bulls,87073838,92522306,90466801,112598201,112601901,128963580,136083814,151964990,165630436,165722496,184248613
27,Jazz,63608425,80138192,105606838,113826156,118910311,136881324,149760719,148738241,133738448,154060898,175744377
28,Grizzlies,83223881,110083520,110700149,125188633,98495848,132022601,117284457,127139520,162649524,165903638,161078924
29,Nets,80258302,82391482,95475397,118850600,118889943,170444633,174811922,159566723,155015136,168312896,151909562

In [3]:
# TEAM SALARIES TABLE ALTERNATE FORM
team_salaries = []

year = 25
for i in range(11):
    url = "https://www.hoopshype.com/salaries/teams/?season=20" + str(year)
    salary_year = pd.read_html(url)[2]
    salary_year = salary_year.rename(columns={"20"+str(year)+"-"+str(year+1):"Salary"})
    salary_year['Season'] = "20"+str(year)+"-"+str(year+1)
    team_salaries.append(salary_year)
    year-=1

team_salaries = pd.concat(team_salaries).drop('Unnamed: 0', axis=1)
team_salaries['Salary'] = team_salaries['Salary'].str.split('$').str.get(-1).str.split(',').str.join("").astype(int)
salary_year['Team'] = salary_year['Team'].str.split().str.get(-1)
team_salaries = team_salaries.drop(labels=['2026-27', '2027-28', '2028-29'], axis=1)
team_salaries = team_salaries.iloc[:, [0,2,1]]

team_salaries

             Team   Season     Salary
0       Cavaliers  2025-26  217367467
1          Knicks  2025-26  211398842
2        Warriors  2025-26  208824825
3         Rockets  2025-26  199794378
4    Timberwolves  2025-26  198498074
..            ...      ...        ...
25           Suns  2015-16   68095365
26          76ers  2015-16   64583220
27           Jazz  2015-16   63608425
28          Magic  2015-16   63199651
29  Trail Blazers  2015-16   61685814

[330 rows x 3 columns]

In [4]:
# TEAM REGULAR SEASON STATS TABLE
team_stats = []

year = 2026
for i in range(11):
    url = "https://www.basketball-reference.com/leagues/NBA_" + str(year) + "_ratings.html"
    TS_year = pd.read_html(url, index_col=0)[0].droplevel(level=0, axis=1)
    TS_year['Season'] = str(year-1)+"-"+str(year)[-2:]
    year-=1
    team_stats.append(TS_year)

team_stats = pd.concat(team_stats)
team_stats['Team'] = team_stats['Team'].str.split().str.get(-1)
team_stats = team_stats.iloc[:, [0,14,1,2,3,4,5,6,7,8,9,10,11,12,13]]

team_stats

Rk,Team,Season,Conf,Div,W,L,W/L%,MOV,ORtg,DRtg,NRtg,MOV/A,ORtg/A,DRtg/A,NRtg/A
1,Thunder,2025-26,W,NW,64,18,0.780,11.15,118.94,107.89,11.05,11.04,118.73,107.78,10.94
2,Spurs,2025-26,W,SW,62,20,0.756,8.30,119.68,111.41,8.27,8.28,119.65,111.40,8.24
3,Celtics,2025-26,E,A,56,26,0.683,7.70,120.82,112.67,8.15,7.37,120.80,113.00,7.80
4,Pistons,2025-26,E,C,60,22,0.732,8.16,118.05,109.81,8.23,7.53,117.70,110.10,7.60
5,Knicks,2025-26,E,A,53,29,0.646,6.33,119.87,113.40,6.47,6.05,119.85,113.67,6.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,Bucks,2015-16,E,C,33,49,0.402,-4.18,105.06,109.65,-4.59,-3.98,105.32,109.69,-4.37
27,Suns,2015-16,W,P,23,59,0.280,-6.66,102.94,109.80,-6.86,-6.32,102.95,109.45,-6.50
28,Nets,2015-16,E,A,21,61,0.256,-7.35,103.74,111.60,-7.86,-7.11,104.06,111.66,-7.61
29,Lakers,2015-16,W,P,17,65,0.207,-9.56,102.29,112.40,-10.12,-8.92,102.49,111.92,-9.43
30,76ers,2015-16,E,A,10,72,0.122,-10.23,99.65,110.15,-10.50,-9.92,99.83,110.01,-10.18

In [5]:
# TEAM PLAYOFF STATS TABLE
team_playoffs = []

year = 2025
for i in range(10):
    url = "https://www.basketball-reference.com/playoffs/NBA_" + str(year) + ".html#all_totals_team-opponent"
    playoffs_year = pd.read_html(url, index_col=0)[20].droplevel(level=0, axis=1).drop(index=np.nan, axis=0)
    playoffs_year = playoffs_year.drop(playoffs_year.columns[14:23], axis=1)
    playoffs_year['Season'] = str(year-1)+"-"+str(year)[-2:]
    year-=1
    team_playoffs.append(playoffs_year)

team_playoffs = pd.concat(team_playoffs).dropna()
team_playoffs['Tm'] = team_playoffs['Tm'].str.split().str.get(-1)
team_playoffs = team_playoffs.rename(columns={'Tm':'Team'})
team_playoffs['Champ'] = 0
team_playoffs.loc[team_playoffs['W'] == 16, 'Champ'] = 1
team_playoffs = team_playoffs.iloc[:, [0,14,15,1,2,3,4,5,6,7,8,9,10,11,12,13]]

team_playoffs

Rk,Team,Season,Champ,Age,W,L,W/L%,PW,PL,ORtg,DRtg,NRtg,Pace,FTr,3PAr,TS%
1.0,Cavaliers,2024-25,0,26.5,5.0,4.0,0.556,7.0,2.0,123.5,111.4,12.1,96.7,0.318,0.467,0.597
2.0,Thunder,2024-25,1,24.7,16.0,7.0,0.696,17.0,6.0,115.4,107.0,8.4,98.9,0.290,0.390,0.566
3.0,Celtics,2024-25,0,29.9,6.0,5.0,0.545,7.0,4.0,114.4,108.4,6.0,91.5,0.273,0.474,0.569
4.0,Timberwolves,2024-25,0,27.6,9.0,6.0,0.600,9.0,6.0,114.6,111.8,2.8,95.1,0.256,0.434,0.574
5.0,Pacers,2024-25,0,26.2,15.0,8.0,0.652,13.0,10.0,115.3,113.3,2.0,98.0,0.292,0.400,0.599
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12.0,Hornets,2015-16,0,26.9,3.0,4.0,0.429,1.0,6.0,99.2,109.0,-9.8,91.0,0.309,0.231,0.494
13.0,Pistons,2015-16,0,24.1,0.0,4.0,0.000,1.0,3.0,109.4,119.2,-9.8,86.8,0.292,0.309,0.559
14.0,Rockets,2015-16,0,28.5,1.0,4.0,0.200,0.0,5.0,92.7,111.8,-19.1,98.4,0.320,0.332,0.467
15.0,Mavericks,2015-16,0,30.4,1.0,4.0,0.200,0.0,5.0,102.1,122.0,-19.9,91.8,0.298,0.264,0.511
16.0,Grizzlies,2015-16,0,30.8,0.0,4.0,0.000,0.0,4.0,90.9,115.6,-24.7,89.1,0.215,0.197,0.455

In [6]:
# NAME MAPS
team_name_map = {
    "ATL": "Hawks",
    "BOS": "Celtics",
    "BKN": "Nets",
    "CHA": "Hornets",
    "CHI": "Bulls",
    "CLE": "Cavaliers",
    "DAL": "Mavericks",
    "DEN": "Nuggets",
    "DET": "Pistons",
    "GSW": "Warriors",
    "HOU": "Rockets",
    "IND": "Pacers",
    "LAC": "Clippers",
    "LAL": "Lakers",
    "MEM": "Grizzlies",
    "MIA": "Heat",
    "MIL": "Bucks",
    "MIN": "Timberwolves",
    "NOP": "Pelicans",
    "NYK": "Knicks",
    "OKC": "Thunder",
    "ORL": "Magic",
    "PHI": "76ers",
    "PHX": "Suns",
    "POR": "Blazers",
    "SAC": "Kings",
    "SAS": "Spurs",
    "TOR": "Raptors",
    "UTA": "Jazz",
    "WAS": "Wizards",
    "2TM": "2TM",
    "3TM": "3TM"
}

player_name_map = {
    "Nikola Jokić": "Nikola Jokic",
    "Luka Dončić": "Luka Doncic",
    "Jonas Valančiūnas": "Jonas Valanciunas",
    "Nikola Vučević": "Nikola Vucevic",
}

In [7]:
# REGULAR SEASON PLAYER DATA
regular_szn_stats = []

year=2026
for i in range(11):
    url = "https://www.basketball-reference.com/leagues/NBA_" +str(year)+ "_per_game.html"

    df = pd.read_html(url)[0]

    df = df[df["Rk"] != "Rk"].copy()

    multi_team_players = df.loc[df["Team"].isin(["2TM", "3TM"]), "Player"]

    df_clean = df[
    ((df["Player"].isin(multi_team_players)) & (df["Team"].isin(["2TM", "3TM"]))) |
    (~df["Player"].isin(multi_team_players))
    ].copy()

    df_clean.reset_index(drop=True, inplace=True)

    df_clean = df_clean.drop(index=len(df_clean)-1, axis=0).drop(columns=['Rk', 'Awards'])

    df_clean['Season'] = str(year-1)+"-"+str(year)[-2:]
    year-=1

    regular_szn_stats.append(df_clean)

p_regular_szn_stats = pd.concat(regular_szn_stats)
p_regular_szn_stats["Team"] = p_regular_szn_stats["Team"].replace(team_name_map)
p_regular_szn_stats["Player"] = p_regular_szn_stats["Player"].replace(player_name_map)

p_regular_szn_stats

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Season
0,Luka Doncic,26.0,Lakers,PG,64.0,64.0,35.8,10.8,22.8,0.476,...,0.6,7.1,7.7,8.3,1.6,0.5,4.0,2.4,33.5,2025-26
1,Shai Gilgeous-Alexander,27.0,Thunder,PG,68.0,68.0,33.2,10.8,19.4,0.553,...,0.6,3.7,4.3,6.6,1.4,0.8,2.2,2.0,31.1,2025-26
2,Anthony Edwards,24.0,Timberwolves,SG,61.0,60.0,35.0,9.9,20.2,0.489,...,0.6,4.4,5.0,3.7,1.4,0.8,2.9,1.9,28.8,2025-26
3,Jaylen Brown,29.0,Celtics,SF,71.0,71.0,34.4,10.4,21.7,0.477,...,1.1,5.8,6.9,5.1,1.0,0.4,3.6,2.7,28.7,2025-26
4,Tyrese Maxey,25.0,76ers,PG,70.0,70.0,38.0,9.9,21.4,0.462,...,0.3,3.8,4.1,6.6,1.9,0.8,2.4,2.2,28.3,2025-26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471,Joe Harris,24.0,Cavaliers,SG,5.0,0.0,3.0,0.2,0.8,0.250,...,0.0,0.6,0.6,0.4,0.0,0.0,0.2,0.2,0.6,2015-16
472,Bruno Caboclo,20.0,Raptors,SF,6.0,1.0,7.2,0.2,2.0,0.083,...,0.2,0.2,0.3,0.2,0.3,0.2,0.7,0.3,0.5,2015-16
473,Sam Dekker,21.0,Rockets,PF,3.0,0.0,2.0,0.0,0.0,NaN,...,0.0,0.3,0.3,0.0,0.3,0.0,0.0,0.0,0.0,2015-16
474,J.J. O'Brien,23.0,Jazz,SF,2.0,0.0,3.0,0.0,0.5,0.000,...,0.0,0.5,0.5,0.0,0.5,0.0,0.0,0.5,0.0,2015-16
475,Nate Robinson,31.0,Pelicans,PG,2.0,1.0,11.5,0.0,0.5,0.000,...,0.0,0.0,0.0,2.0,0.5,0.0,0.0,2.5,0.0,2015-16

In [8]:
# PLAYOFF PLAYER DATA
p_playoff_stats = []

year=2025
for i in range(10):
    url = "https://www.basketball-reference.com/leagues/NBA_" + str(year) + "_per_game.html"

    df = pd.read_html(url)[1]

    df = df[df["Rk"] != "Rk"].copy()

    multi_team_players = df.loc[df["Team"].isin(["2TM", "3TM"]), "Player"]

    df_clean = df[
    ((df["Player"].isin(multi_team_players)) & (df["Team"].isin(["2TM", "3TM"]))) |
    (~df["Player"].isin(multi_team_players))
    ].copy()

    df_clean.reset_index(drop=True, inplace=True)

    df_clean = df_clean.drop(index=len(df_clean)-1, axis=0).drop(columns=['Rk', 'Awards'])

    df_clean['Season'] = str(year-1)+"-"+str(year)[-2:]
    year-=1

    p_playoff_stats.append(df_clean)

p_playoff_stats = pd.concat(p_playoff_stats)
p_playoff_stats["Team"] = p_playoff_stats["Team"].replace(team_name_map)
p_playoff_stats["Player"] = p_playoff_stats["Player"].replace(player_name_map)

p_playoff_stats

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Season
0,Giannis Antetokounmpo,30.0,Bucks,PF,5.0,5.0,37.6,12.0,19.8,0.606,...,3.8,11.6,15.4,6.6,1.0,1.0,4.6,2.4,33.0,2024-25
1,Luka Doncic,25.0,Lakers,PG,5.0,5.0,41.6,9.4,20.8,0.452,...,0.4,6.6,7.0,5.8,1.0,0.6,4.0,3.2,30.2,2024-25
2,Shai Gilgeous-Alexander,26.0,Thunder,PG,23.0,23.0,37.0,10.1,21.9,0.462,...,1.0,4.3,5.3,6.5,1.7,0.9,2.6,2.8,29.9,2024-25
3,Donovan Mitchell,28.0,Cavaliers,SG,9.0,9.0,32.0,9.6,21.6,0.443,...,1.2,3.4,4.7,3.9,1.9,0.3,1.9,2.0,29.6,2024-25
4,Paolo Banchero,22.0,Magic,PF,5.0,5.0,39.4,10.8,24.8,0.435,...,2.4,6.0,8.4,4.2,0.6,0.8,3.0,3.6,29.4,2024-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,John Holland,27.0,Celtics,SF,1.0,0.0,1.0,0.0,1.0,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015-16
211,Pablo Prigioni,38.0,Clippers,PG,5.0,0.0,5.2,0.0,1.0,0.000,...,0.4,0.2,0.6,1.4,0.0,0.0,0.6,1.6,0.0,2015-16
212,Noah Vonleh,20.0,Blazers,PF,6.0,0.0,2.0,0.0,0.5,0.000,...,0.2,0.5,0.7,0.3,0.3,0.0,0.0,0.2,0.0,2015-16
213,Briante Weber,23.0,Heat,PG,2.0,0.0,3.0,0.0,0.5,0.000,...,0.0,0.0,0.0,0.5,0.5,0.0,0.0,0.5,0.0,2015-16
214,C.J. Wilcox,25.0,Clippers,SG,2.0,0.0,3.5,0.0,0.5,0.000,...,0.0,0.5,0.5,0.5,0.0,0.0,0.0,0.5,0.0,2015-16

In [9]:
# PLAYER SALARIES
def get_year_salaries_until_stop(year):
    pages = []

    for page in range(1, 15):
        url = f"https://www.espn.com/nba/salaries/_/year/{year}/page/{page}/seasontype/5"
        try:
            tables = pd.read_html(url)
        except Exception:
            break

        df = tables[0].copy()

        if df.empty:
            break

        pages.append(df)

    if pages:
        return pd.concat(pages, ignore_index=True)
    return pd.DataFrame()

player_salaries = []

year = 2026
for i in range(11):
    df = get_year_salaries_until_stop(year)
    df["Season"] = str(year-1)+"-"+str(year)[-2:]
    player_salaries.append(df)
    year-=1

player_salaries = pd.concat(player_salaries)
player_salaries = player_salaries[player_salaries.loc[:,1] != 'NAME'].drop(columns=0)
player_salaries = player_salaries.rename(columns={1:'Player', 2:'Team', 3:'Salary'})
player_salaries['Player'] = player_salaries['Player'].str.split(',').str.get(0)
player_salaries['Salary'] = player_salaries['Salary'].str.split('$').str.get(-1).str.split(',').str.join("").astype(int)
player_salaries['Team'] = player_salaries['Team'].str.split().str.get(-1)

player_salaries

                     Player       Team    Salary   Season
1             Stephen Curry   Warriors  59606817  2025-26
2               Joel Embiid      76ers  55224526  2025-26
3              Nikola Jokic    Nuggets  55224526  2025-26
4              Kevin Durant    Rockets  54708609  2025-26
5             Anthony Davis  Mavericks  54126450  2025-26
..                      ...        ...       ...      ...
554         Orlando Johnson   Pelicans     55722  2015-16
555            Phil Pressey       Suns     55722  2015-16
556         Elliot Williams  Grizzlies     55722  2015-16
557          Cory Jefferson       Suns     49709  2015-16
558  Thanasis Antetokounmpo     Knicks     30888  2015-16

[5664 rows x 4 columns]